### ISSUE TITLE
[Bug] ”Turn screen off during mirroring“ toggle doesn't works.

### ISSUE THREAD

**Issue by FullCombos** [yume-chan/tango-feedback#12] opened 2023-12-01 03:39 UTC
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the problem I had

### The environment Tango is running in

Windows 10, Edge 119.0.2151.93 

### The device you're connecting to

Google Pixel 7, Android 14

### What did you do and what happened?

Enable "Turn screen off during mirroring", then start scrcpy, screen still on.

**Comment by yume-chan** [comment] 2023-12-01 06:49
Thanks for reporting!

This issue is caused by Android internal changes. We already have a fix (https://github.com/Genymobile/scrcpy/pull/4456), which will be released soon.

**Comment by yume-chan** [comment] 2023-12-05 04:57
A new version is now online.

Note that because of another change in Scrcpy, turning screen off is not functioning when video source is set to camera. It will be fixed in next version.

**Closed as completed by yume-chan** 2023-12-05 04:57 UTC
Labels: bug
